version: '3.3'
volumes: 
  giftogo-data-dir:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: /Users/bruger/drives/giftogo-postgres
services:
  pg:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - giftogo-data-dir:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dockgiftogo"

  giftogo:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/giftogo-app
    environment:
      DB_DIALECT: "postgres"
      DB_HOST: "pg"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "dockgiftogo"
    ports:
      - "8005:8005"
    depends_on: 
      - pg