version: '3.3'
volumes: 
  mysql-data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sarah/mysql
  giftogo-app-dir:
    driver: local
    driver_opts: 
      o: bind
      type: none
      device: /home/sarah/projects/giftogo/giftogo
services:
  my-mysql:
    image: mysql:5.7.18
    environment: 
      MYSQL_ROOT_PASSWORD: "imgettingitroot"
    ports: 
      - "3306:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
  giftogo:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - giftogo-app-dir:/giftogo-app
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "my-mysql"
      DB_USERNAME: "root"
      DB_PASSWORD: "imgettingitroot"
      DB_PORT: "3306"
      DB_DATABASE: "dockgiftogo"
    ports:
      - "8001:8000"
    depends_on: 
      - my-mysql